services:
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENER=PLAINTEXT://localhost:9092
      - KAFKA_ADVERTISED_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=deepaanna
      - DOCKER_INFLUXDB_INIT_PASSWORD=Newman1124!
      - DOCKER_INFLUXDB_INIT_ORG=halifax_project
      - DOCKER_INFLUXDB_INIT_BUCKET=air_quality
